services:
  postgres:
    image: postgres:15
    container_name: {{PROJECT_NAME}}-db
    environment:
      POSTGRES_DB: {{PROJECT_NAME_SNAKE}}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdev123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
